<?php
/**
 * @file
 *  Helps site builders and module developers investigate a site.
 */

/**
 * Implements hook_form_alter() to show each form's indentifier.
 *
 * More description after an empty line.
 */
function xray_form_alter(&$form, &$form_state, $form_id) {
  //debug($form, $form_id, TRUE);
  $form['xray_display_form_id'] = array(
    '#type' => 'item',
    '#title' => t('Form ID'),
    '#markup' => $form_id,
    '#theme_wrappers' => array('container__xray__form'),
    '#attributes' => array('class' => array('xray')),
    '#weight' => -100,
  );
}

/**
 * Implements hook_help().
 */
function xray_help($path, $arg) {
  switch($path) {
    case 'admin/appearance':
      return t(_xray_help_admin_appearance());
    case 'admin/structure':
      return t('This site has stuff');
  }
}

/**
 * Fetch information about themes
 */
function xray_stats_enabled_themes() {
  $themes = list_themes();
  $num_themes = count($themes);
  $num_enabled = 0;
  $summaries = array();
  //print_r($themes);
  $num_hidden = 1;
  
  foreach ($themes as $themename => $theme) {
    //print(' HERE theme[filename] = ' . $theme->filename);
    if (isset($theme->info['hidden']) && $theme->info['hidden']) {
      $num_hidden++;
      //print(' themename = ' . $themename);
    }
    else {
      if ($theme->status) {
        $num_enabled++;
        $summaries[$theme->info['name']] = array(
          'regions' => count($theme->info['regions']),
          'overlay_regions' => count($theme->info['overlay_regions']),
          'regions_hidden' => count($theme->info['regions_hidden']),
          'features' => count($theme->info['features']),
          //'kindsofstylesheets' => count($themes->info['stylesheets']),
          'allstylesheets' => isset($theme->info['stylesheets']['all']) ? count($theme->info['stylesheets']['all']) : 0,
        );
      }
    }
  }
  return compact('num_themes','num_hidden','num_enabled','summaries');
}
/**
 * Help text for the admin/appearance page
 */
function _xray_help_admin_appearance() {
  //debug(list_themes());
  $output = '';
  $data = xray_stats_enabled_themes();
  $output .= format_plural(
    $data['num_hidden'],
    'There is one hidden theme.',
    'There are @count hidden themes.'
  );
  $output .= '<br />' . format_plural($data['num_enabled'],
                                      'There is one theme enabled.',
                                      'There are @count themes enabled.'
                                      );
  //print_r($data);
  
  return $output;
  //return theme('xray_help', array('text' => $output));
}

//menu_rebuild();
/**
 * Implements hook_menu().
 */
function xray_menu() {
  $items['admin/reports/xray'] = array(
    'title' => 'X-ray technical site overview',
    'description' => 'See the guts of the site',
    'page callback' => 'xray_overview_page',
    'access callback' => TRUE,
  );
  $items['admin/reports/xray/overview'] = array(
    'title' => 'Overview',
    'description' => "Overview of the site's internals.",
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
  
}


